routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(['prefix' => '/', 'middleware' => 'web', 'namespace' => 'frontend'], function () {
  Route::get('/', 'PagesController@home')->name('home');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'backend'], function () {
  Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
  Route::resource('/post', 'PostController');
  Route::resource('/category', 'CategoryController');
  Route::get('/change_password/{id}', 'UserController@change_password')->name('change_password');
  Route::patch('/save_change_password/{id}', 'UserController@save_change_password')->name('save_change_password');

  Route::group(['prefix' => 'datatables'], function () {
    Route::get('/', ['as' => 'datatables.index', 'uses' => 'DatatablesController@index']);
    // Route::get('users', ['as' => 'datatables.users', 'uses' => 'DatatablesController@users']);
    Route::get('categories', ['as' => 'datatables.categories', 'uses' => 'DatatablesController@categories']);
    Route::get('posts', ['as' => 'datatables.posts', 'uses' => 'DatatablesController@posts']);
  });
});

// Route for social login
Route::get('auth/github', 'Auth\LoginController@redirectToProvider');
Route::get('auth/github/callback', 'Auth\LoginController@handleProviderCallback');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  protected $fillable = ['name', 'slug'];

  public function posts()
  {
    return $this->hasMany('App\Post');
  }

  public function user()
  {
    return $this->belongsTo('App\User');
  }
}

app/Http/Controllers/backend/BackendController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use View;

class BackendController extends BaseController
{
  use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
  /**
   * @var AdminLte
   */
  public function __construct()
  {
    View::composers([
      'App\Http\BackendComposers\ViewComposer' => '*',
    ]);
  }
}

app/Http/Controllers/backend/CategoryController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\Category;

class CategoryController extends BackendController
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $categories = Category::all();
    return view('backend.category.index', compact('categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('backend.category.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required',
      'slug' => 'required|unique:categories',
    ]);

    $category          = new Category;
    $category->name    = $request->name;
    $category->slug    = $request->slug;
    $category->user_id = \Auth::user()->id;

    if ($category->save()) {
      return redirect()->route('category.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($category->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Category $category)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Category $category)
  {
    return view('backend.category.edit', compact('category'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Category $category)
  {
    $category->update($request->all());
    return redirect()->route('category.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Category $category)
  {
    if ($category->delete()) {
      return redirect()->route('category.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('category.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

class DashboardController extends BackendController
{
  public function index()
  {
    return view('backend.dashboard.index');
  }
}

app/Http/Controllers/backend/DatatablesController.php
<?php

namespace App\Http\Controllers\backend;

use Datatables;
use Illuminate\Http\Request;
use \App\Category;
use \App\Post;
use \App\User;

class DatatablesController extends BackendController
{
  /**
   * Process datatables ajax request.
   *
   * @return \Illuminate\Http\JsonResponse
   */
  public function users()
  {
    return Datatables::of(User::all())
      ->editColumn('is_admin', '@if($is_admin) Admin @else Operator @endif')
      ->make(true);
  }

  public function categories()
  {
    return Datatables::of(Category::query())
      ->editColumn('created_at', function ($data) {return $data->created_at->format('d F Y');})
      ->editColumn('user_id', function ($data) {return $data->user->name;})
      ->addColumn('actions', '<a href="{{ route(\'category.edit\', $slug) }}" class="fa fa-edit btn btn-sm btn-primary">Edit</a>
            {{postLink(route("category.destroy",$slug),"<span class=\'fa fa-trash btn btn-danger btn-sm\'>Delete</span>","Are you sure to delete?")}}')
      ->make(true);
  }

  public function posts()
  {
    return Datatables::of(Post::query())
      ->addColumn('thumbnail', '<img src="/thumbs/{{ $image }}" alt="">')
      ->editColumn('user_id', function ($data) {return $data->user->name;})
      ->addColumn('actions', '<a href="{{ route(\'post.show\', $slug) }}" class="fa fa-eye btn btn-sm btn-default">Show</a>
          <a href="{{ route(\'post.edit\', $slug) }}" class="fa fa-edit btn btn-sm btn-primary">Edit</a>
            {{postLink(route("post.destroy",$slug),"<span class=\'fa fa-trash btn btn-danger btn-sm\'>Delete</span>","Are you sure to delete?")}}')
      ->make(true);
  }
}

app/Http/Controllers/backend/PostController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\Category;
use \App\Post;

class PostController extends BackendController
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $posts      = Post::all();
    $categories = Category::all();
    return view('backend.post.index', compact('posts', 'categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $categories = Category::all();
    return view('backend.post.create', compact('categories'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'category_id'       => 'required',
      'title'             => 'required',
      'slug'              => 'required|unique:posts',
      'short_description' => 'required',
      'content'           => 'required',
      'image'             => 'required',
      // 'thumbnail'         => 'required',
      'publish_on'        => 'required|date',
    ]);

    $post                    = new Post;
    $post->category_id       = $request->category_id;
    $post->user_id           = \Auth::user()->id;
    $post->title             = $request->title;
    $post->slug              = $request->slug;
    $post->short_description = $request->short_description;
    $post->content           = $request->content;
    $post->image             = $request->image;
    $post->publish_on        = $request->publish_on;
    // $post->thumbnail         = $request->thumbnail;

    if ($post->save()) {
      return redirect()->route('post.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($post->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Post $post)
  {
    return view('backend.post.show', compact('post'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Post $post)
  {
    $categories = Category::all();
    return view('backend.post.edit', compact('post', 'categories'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Post $post)
  {
    $post->update($request->all());
    return redirect()->route('post.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Post $post)
  {
    if ($post->delete()) {
      return redirect()->route('post.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('post.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

app/Http/Controllers/backend/UserController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\User;

class UserController extends BackendController
{
  /**
   * Display change password view
   */
  public function change_password($id)
  {
    $user = User::find($id);
    return view('backend.user.change_password', compact('user'));
  }

  public function save_change_password(Request $request, $id)
  {
    $this->validate($request, [
      'password' => 'required|min:6|confirmed',
    ]);
    $user = User::find($id);
    if (\Hash::check($request->current_password, $user->password) || \Hash::check('password', $user->password)) {
      $user->update(['password' => bcrypt($request->password)]);
      flash('Password Succesfully Changed!');
      return redirect()->route('dashboard');
    } else {
      flash('Current Password is wrong!', 'danger');
      return redirect()->route('change_password', $user->id);
    }
  }
}

resources/views/backend/category/_form.blade.php
<div class="col-md-4">
    <div class="form-group has-feedback {{ $errors->has('category') ? 'has-error' : '' }}">
        <label for="category">Name</label>
        <input type="text" name="name" class="form-control" value="{{ empty($category) ? old('name') : $category->name }}" id="category_name">
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('slug') ? 'has-error' : '' }}">
        <label for="slug">Slug</label>
        <input type="text" name="slug" class="form-control" value="{{ empty($category) ? old('slug') : $category->slug }}" id="category_slug">
        @if ($errors->has('slug'))
            <span class="help-block">
                <strong>{{ $errors->first('slug') }}</strong>
            </span>
        @endif
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</div>

@section('js')
    <script>
        $(document).ready(function() {
            var slug = $('#category_slug');
            $('#category_name').on('blur', function() {
                slug.val(convertToSlug($(this).val()));
            });
        });
    </script>
@stop

resources/views/backend/category/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Category')

@section('content_header')
    <h1>Create Category</h1>
@stop

@section('content')
<form action="{{ route('category.store') }}" method="post">
    {!! csrf_field() !!}
    @include('backend.category._form')
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/backend/category/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Category')

@section('content_header')
    <h1>Edit Category</h1>
@stop

@section('content')
<form action="{{ route('category.update', $category->slug) }}" method="post">
    {!! csrf_field() !!}
    <input type="hidden" name="_method" value="put">
    @include('backend.category._form')
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/backend/category/index.blade.php
@extends('layouts.admin')

@section('title', 'Categories')

@section('content_header')
    <h1>Data Categories</h1>
@stop

@section('content')
<a href="{{ route('category.create') }}" class="btn btn-primary btn-md">Create Category</a>
<div class="clearfix"></div>
<br>
<table class="table table-striped table-hover table-bordered" id="category-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Created By</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
</table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@push('js')
<script>
$(function() {
    $('#category-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.categories') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'slug', name: 'slug' },
            { data: 'user_id', name: 'user_id' },
            { data: 'created_at', name: 'created_at' },
            { data: 'actions', name: 'actions', searchable: false }
        ]
    });
});
</script>
@endpush