routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(['prefix' => '/', 'middleware' => 'web', 'namespace' => 'frontend'], function () {
  Route::get('/', 'PagesController@home')->name('home');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'backend'], function () {
  Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
  Route::resource('/post', 'PostController');
  Route::resource('/category', 'CategoryController');
  Route::get('/change_password/{id}', 'UserController@change_password')->name('change_password');
  Route::patch('/save_change_password/{id}', 'UserController@save_change_password')->name('save_change_password');

  Route::group(['prefix' => 'datatables'], function () {
    Route::get('/', ['as' => 'datatables.index', 'uses' => 'DatatablesController@index']);
    // Route::get('users', ['as' => 'datatables.users', 'uses' => 'DatatablesController@users']);
    Route::get('categories', ['as' => 'datatables.categories', 'uses' => 'DatatablesController@categories']);
    Route::get('posts', ['as' => 'datatables.posts', 'uses' => 'DatatablesController@posts']);
  });
});

// Route for social login
Route::get('auth/github', 'Auth\LoginController@redirectToProvider');
Route::get('auth/github/callback', 'Auth\LoginController@handleProviderCallback');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  protected $fillable = ['category_id', 'title', 'slug', 'short_description', 'content', 'image', 'thumbnail', 'publish_on'];
  protected $dates    = ['publish_on'];

  public function category()
  {
    return $this->belongsTo('App\Category');
  }

  public function user()
  {
    return $this->belongsTo('App\User');
  }
}

app/Http/Controllers/backend/BackendController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use View;

class BackendController extends BaseController
{
  use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
  /**
   * @var AdminLte
   */
  public function __construct()
  {
    View::composers([
      'App\Http\BackendComposers\ViewComposer' => '*',
    ]);
  }
}

app/Http/Controllers/backend/CategoryController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\Category;

class CategoryController extends BackendController
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $categories = Category::all();
    return view('backend.category.index', compact('categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('backend.category.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required',
      'slug' => 'required|unique:categories',
    ]);

    $category          = new Category;
    $category->name    = $request->name;
    $category->slug    = $request->slug;
    $category->user_id = \Auth::user()->id;

    if ($category->save()) {
      return redirect()->route('category.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($category->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Category $category)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Category $category)
  {
    return view('backend.category.edit', compact('category'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Category $category)
  {
    $category->update($request->all());
    return redirect()->route('category.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Category $category)
  {
    if ($category->delete()) {
      return redirect()->route('category.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('category.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

class DashboardController extends BackendController
{
  public function index()
  {
    return view('backend.dashboard.index');
  }
}

app/Http/Controllers/backend/DatatablesController.php
<?php

namespace App\Http\Controllers\backend;

use Datatables;
use Illuminate\Http\Request;
use \App\Category;
use \App\Post;
use \App\User;

class DatatablesController extends BackendController
{
  /**
   * Process datatables ajax request.
   *
   * @return \Illuminate\Http\JsonResponse
   */
  public function users()
  {
    return Datatables::of(User::all())
      ->editColumn('is_admin', '@if($is_admin) Admin @else Operator @endif')
      ->make(true);
  }

  public function categories()
  {
    return Datatables::of(Category::query())
      ->editColumn('created_at', function ($data) {return $data->created_at->format('d F Y');})
      ->editColumn('user_id', function ($data) {return $data->user->name;})
      ->addColumn('actions', '<a href="{{ route(\'category.edit\', $slug) }}" class="fa fa-edit btn btn-sm btn-primary">Edit</a>
            {{postLink(route("category.destroy",$slug),"<span class=\'fa fa-trash btn btn-danger btn-sm\'>Delete</span>","Are you sure to delete?")}}')
      ->make(true);
  }

  public function posts()
  {
    return Datatables::of(Post::query())
      ->addColumn('thumbnail', '<img src="/thumbs/{{ $image }}" alt="">')
      ->editColumn('user_id', function ($data) {return $data->user->name;})
      ->addColumn('actions', '<a href="{{ route(\'post.show\', $slug) }}" class="fa fa-eye btn btn-sm btn-default">Show</a>
          <a href="{{ route(\'post.edit\', $slug) }}" class="fa fa-edit btn btn-sm btn-primary">Edit</a>
            {{postLink(route("post.destroy",$slug),"<span class=\'fa fa-trash btn btn-danger btn-sm\'>Delete</span>","Are you sure to delete?")}}')
      ->make(true);
  }
}

app/Http/Controllers/backend/PostController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\Category;
use \App\Post;

class PostController extends BackendController
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $posts      = Post::all();
    $categories = Category::all();
    return view('backend.post.index', compact('posts', 'categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $categories = Category::all();
    return view('backend.post.create', compact('categories'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'category_id'       => 'required',
      'title'             => 'required',
      'slug'              => 'required|unique:posts',
      'short_description' => 'required',
      'content'           => 'required',
      'image'             => 'required',
      // 'thumbnail'         => 'required',
      'publish_on'        => 'required|date',
    ]);

    $post                    = new Post;
    $post->category_id       = $request->category_id;
    $post->user_id           = \Auth::user()->id;
    $post->title             = $request->title;
    $post->slug              = $request->slug;
    $post->short_description = $request->short_description;
    $post->content           = $request->content;
    $post->image             = $request->image;
    $post->publish_on        = $request->publish_on;
    // $post->thumbnail         = $request->thumbnail;

    if ($post->save()) {
      return redirect()->route('post.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($post->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Post $post)
  {
    return view('backend.post.show', compact('post'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Post $post)
  {
    $categories = Category::all();
    return view('backend.post.edit', compact('post', 'categories'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Post $post)
  {
    $post->update($request->all());
    return redirect()->route('post.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Post $post)
  {
    if ($post->delete()) {
      return redirect()->route('post.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('post.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

app/Http/Controllers/backend/UserController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use \App\User;

class UserController extends BackendController
{
  /**
   * Display change password view
   */
  public function change_password($id)
  {
    $user = User::find($id);
    return view('backend.user.change_password', compact('user'));
  }

  public function save_change_password(Request $request, $id)
  {
    $this->validate($request, [
      'password' => 'required|min:6|confirmed',
    ]);
    $user = User::find($id);
    if (\Hash::check($request->current_password, $user->password) || \Hash::check('password', $user->password)) {
      $user->update(['password' => bcrypt($request->password)]);
      flash('Password Succesfully Changed!');
      return redirect()->route('dashboard');
    } else {
      flash('Current Password is wrong!', 'danger');
      return redirect()->route('change_password', $user->id);
    }
  }
}

resources/views/backend/post/_form.blade.php
<div class="form-group has-feedback {{ $errors->has('category_id') ? 'has-error' : '' }}">
    <label for="nama">Category</label>
    <select name="category_id" class="form-control select2">
        <option value="">Pleas Select</option>
        @foreach ($categories as $category)
        <option value="{{ $category->id }}" {{ empty($post) ? '' : $post->category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
        @endforeach
    </select>
    @if ($errors->has('category_id'))
    <span class="help-block">
        <strong>{{ $errors->first('category_id') }}</strong>
    </span>
    @endif
</div>
<div class="form-group has-feedback {{ $errors->has('title') ? 'has-error' : '' }}">
    <label for="nama">Title</label>
    <input type="text" name="title" class="form-control" value="{{ empty($post) ? old('title') : $post->title }}" id="post_title">
    @if ($errors->has('title'))
    <span class="help-block">
        <strong>{{ $errors->first('title') }}</strong>
    </span>
    @endif
</div>
<div class="form-group has-feedback {{ $errors->has('short_description') ? 'has-error' : '' }}">
    <label for="short_description">Short Description</label>
    <textarea name="short_description" id="short_description" class="form-control">{{ empty($post) ? old('short_description') : $post->short_description }}</textarea>
    @if ($errors->has('short_description'))
    <span class="help-block">
        <strong>{{ $errors->first('short_description') }}</strong>
    </span>
    @endif
</div>
<div class="form-group has-feedback {{ $errors->has('content') ? 'has-error' : '' }}">
    <label for="content">Content</label>
    <textarea name="content" id="content" class="form-control editor">{{ empty($post) ? old('content') : $post->content }}</textarea>
    @if ($errors->has('content'))
    <span class="help-block">
        <strong>{{ $errors->first('content') }}</strong>
    </span>
    @endif
</div>
<div class="form-group has-feedback {{ $errors->has('image') ? 'has-error' : '' }}">
    <label for='image' class='col-md-2 control-label'>Image</label>
    <input class="form-control required" onfocus="$('.filemanager').trigger('click')" readonly type="text" placeholder="File name" id="image" name="image">
    <div class="input-group-addon">
        <a class="filemanager btn btn-danger" href="{{url('/')}}/filemanager/dialog.php?type=1&field_id=image&relative_url=1"><span class="glyphicon glyphicon-zoom-in"></span></a>
    </div>
    @if ($errors->has('image'))
    <span class="help-block">
        <strong>{{ $errors->first('image') }}</strong>
    </span>
    @endif
</div>
<img src="{{ empty($post) ? '' : '/thumbs/'.$post->image }}" alt="" id="image_preview" style="margin-top:15px;max-height:100px;">
<div class="form-group has-feedback {{ $errors->has('slug') ? 'has-error' : '' }}">
    <label for="nama">Slug</label>
    <input type="text" name="slug" class="form-control" value="{{ empty($post) ? old('slug') : $post->slug }}" id="post_slug">
    @if ($errors->has('slug'))
    <span class="help-block">
        <strong>{{ $errors->first('slug') }}</strong>
    </span>
    @endif
</div>
<div class="form-group has-feedback {{ $errors->has('publish_on') ? 'has-error' : '' }}">
    <label for="publish_on">Publish On</label>
    <input type="text" name="publish_on" class="form-control date" value="{{ empty($post) ? old('publish_on') : $post->publish_on }}">
    @if ($errors->has('publish_on'))
    <span class="help-block">
        <strong>{{ $errors->first('publish_on') }}</strong>
    </span>
    @endif
</div>
<button type="submit" class="btn btn-primary btn-flat">Save</button>

@section('js')
    <script>
        $(document).ready(function() {
            var slug = $('#post_slug');
            $('#post_title').on('blur', function() {
                slug.val(convertToSlug($(this).val()));
            });
        });
    </script>
@stop

resources/views/backend/post/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Post')

@section('content_header')
    <h1>Create Post</h1>
@stop

@section('content')
<form action="{{ route('post.store') }}" method="post">
    {!! csrf_field() !!}
    @include('backend.post._form')
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/backend/post/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Post')

@section('content_header')
    <h1>Edit Post</h1>
@stop

@section('content')
<form action="{{ route('post.update', $post->slug) }}" method="post">
    {!! csrf_field() !!}
    <input type="hidden" name="_method" value="put">
    @include('backend.post._form')
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/backend/post/index.blade.php
@extends('layouts.admin')

@section('title', 'Posts')

@section('content_header')
    <h1>Data Posts</h1>
@stop

@section('content')
@if($categories->count() > 0)
  <a href="{{ route('post.create') }}" class="btn btn-primary btn-md">Create Post</a>
  <div class="clearfix"></div>
  <br>
@endif
<table class="table table-striped table-hover table-bordered" id="post-table">
  <thead>
    <tr>
      <th>ID Posts</th>
      <th>Title</th>
      <th>Category</th>
      <th>Created By</th>
      <th>Publish On</th>
      <th>Thumbnail</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
</table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@push('js')
<script>
$(function() {
    $('#post-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.posts') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'title', name: 'title' },
            { data: 'category_id', name: 'category_id', searchable: false },
            { data: 'user_id', name: 'user_id', searchable: false },
            { data: 'publish_on', name: 'publish_on' },
            { data: 'thumbnail', name: 'thumbnail', searchable: false },
            { data: 'created_at', name: 'created_at' },
            { data: 'actions', name: 'actions', searchable: false }
        ]
    });
});
</script>
@endpush

resources/views/backend/post/show.blade.php
@extends('layouts.admin')

@section('title', 'Show Post')

@section('content_header')
    <h1>Show Post</h1>
@stop

@section('content')
<div class="col-xs-12"><img src="/source/{{ $post->image }}" alt=""></div>
<h1>{{ $post->title }}</h1>
<h5><span class="glyphicon glyphicon-time"></span> Post by {{ $post->user->name }}, {{ $post->publish_on->format('d F Y') }}.</h5>
<h5><span class="label label-danger">{{ $post->category->name }}</span></h5><br>
{!! $post->content !!}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop